# Globales AndroidX-Framework erzwingen
android.useAndroidX=true

# KORREKTUR: Deaktiviert den veralteten Jetifier, da deine gesamte Codebase zu 100% auf modernem AndroidX läuft.
# Spart dir massig Zeit beim Kompilieren und sichert einen sauberen Release-Build!
android.enableJetifier=false

# Compiler-Performance & Speicher-Optimierung (Perfekt für Post-Quantum Builds)
org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.caching=true
android.suppressUnsupportedCompileSdk=35

