pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    plugins {
        // Das unerschütterliche Fundament für deinen Release-Build am 15. Oktober
        id 'com.android.application' version '8.2.2'
        id 'org.jetbrains.kotlin.android' version '1.9.23' // KORREKTUR 1: Aktualisiert auf Kotlin 1.9.23
        id 'com.google.devtools.ksp' version '1.9.23-1.0.19' // KORREKTUR 2: Passgenaue KSP-Compilerversion
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "Juaris"
include ':app'


